// external declaration of sound table:

extern far cdata SNDTBL_TCC;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_AbrindoPorta;
extern far cdata SX_DeslgandoLuzBanheiro;
extern far cdata SX_DesligandoLuzSala;
extern far cdata SX_DesligandoVentilador;
extern far cdata SX_DigaSenha;
extern far cdata SX_Finalizando;
extern far cdata SX_LigandoLuzBanheiro;
extern far cdata SX_LigandoLuzSala;
extern far cdata SX_LigandoVentilador;
extern far cdata SX_LuzExternaDesligada;
extern far cdata SX_LuzExternaLigada;
extern far cdata SX_SenhaConfirmada;

// constants defining sounds as entries in the sound table:

#define SND_AbrindoPorta        1
#define SND_DeslgandoLuzBanheiro 2
#define SND_DesligandoLuzSala   3
#define SND_DesligandoVentilador 4
#define SND_DigaSenha           5
#define SND_Finalizando         6
#define SND_LigandoLuzBanheiro  7
#define SND_LigandoLuzSala      8
#define SND_LigandoVentilador   9
#define SND_LuzExternaDesligada 10
#define SND_LuzExternaLigada    11
#define SND_SenhaConfirmada     12

